mysite/urls.py
from django.conf.urls import patterns, include, url
from mysite.views import hello, current_datetime, hours_ahead
from books import views
from contact import views_contact

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	url('^hello/$', hello),
	url('^time/$', current_datetime),
	url(r'^time/plus/(\d{1,2})/$', hours_ahead),
    url(r'^search/$', views.search),
    url(r'^contact/$', views_contact.contact),
    url(r'^contact/thanks/$', views_contact.thanks),
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

books/models.py
from django.db import models

# Create your models here.

class Publisher(models.Model):
	name = models.CharField(max_length=30)
	address = models.CharField(max_length=50)
	city = models.CharField(max_length=60)
	state_province = models.CharField(max_length=30)
	country = models.CharField(max_length=50)
	website = models.URLField()

	def __unicode__(self):
		return self.name

	class Meta:
		ordering = ['name']

class Author(models.Model):
	first_name = models.CharField(max_length=30)
	last_name = models.CharField(max_length=40)
	email = models.EmailField('e-mail', blank=True)

	def __unicode__(self):
		return u'%s %s' % (self.first_name, self.last_name)

class Book(models.Model):
	title = models.CharField(max_length=100)
	authors = models.ManyToManyField(Author)
	publisher = models.ForeignKey(Publisher)
	publication_date = models.DateField(blank=True, null=True)

	def __unicode__(self):
		return self.title

contact/forms.py
from django import forms

class ContactForm(forms.Form):
	subject = forms.CharField(max_length=100)
	email = forms.EmailField(required=False, label='Your e-mail address')
	message = forms.CharField(widget=forms.Textarea)

	def clean_message(self):
		message = self.cleaned_data['message']
		num_words = len(message.split())
		if num_words < 4:
			raise forms.ValidationError("Not enough words!")
		return message

books/views.py
# Create your views here.

from django.shortcuts import render_to_response
from django.http import HttpResponse
from books.models import Book

def search(request):
	errors = []
	if 'q' in request.GET:
		q = request.GET['q']
		if q:
			if len(q) > 20:
				errors.append('Please enter at most 20 characters.')
			else:
				books = Book.objects.filter(title__icontains=q)
				return render_to_response('search_results.html', {'books': books, 'query': q})
		else:
			errors.append('Enter a search term.')
	return render_to_response('search_form.html', {'errors': errors})

mysite/views.py
from django.shortcuts import render_to_response
import datetime

def hello(request):
	return HttpResponse("Hello world")

def current_datetime(request):
	now = datetime.datetime.now()
	return render_to_response('current_datetime.html', {'current_date': now})

def hours_ahead(request, offset):
	try:
		offset = int(offset)
	except:
		raise Http404()
	dt = datetime.datetime.now() + datetime.timedelta(hours=offset)
	return render_to_response('hours_ahead.html', {'next_time': dt})

mysite/templates/base.html
<!DOCTYPE HTML>
<html lang="en">
<head>
	<title>{% block title %}{% endblock %}</title>
</head>
<body>
	
	<h1>{% block header %}{% endblock %}</h1>
	{% block content %}{% endblock %}
	{% block footer %}
	<hr>
	<p>Thanks for visiting my site.</p>
	{% endblock %}
</body>
</html>

mysite/templates/contact_form.html
<html>
<head>
	<title>Contact us</title>
</head>
<body>
	<h1>Contact us</h1>
	{% if form.errors %}
	<p style="color: red;">
		Please correct the error{{ form.errors|pluralize }} below.
	</p>
	{% endif %}
	<form action="" method="post">
		{% csrf_token %}
		<div class="field">
			{{ form.subject.errors }}
			<label for="id_subject">Subject:</label>
			{{ form.subject }}
		</div>
		<div class="field">
			{{ form.email.errors }}
			<label for="id_email">Your e-mail address:</label>
			{{ form.email }}
		</div>
		<div class="field{% if form.message.errors %} errors{% endif %}">
			{% if form.message.errors %}
			<ul>
				{% for error in form.message.errors %}
				<li><strong>{{ error }}</strong></li>
				{% endfor %}
			</ul>
			{% endif %}
			<label for="id_message">Message:</label>
			{{ form.message }}
		</div>
		<input type="submit" value="Submit">
	</form>
</body>
</html>

mysite/templates/contact_thanks.html
{% extends "base.html" %}

{% block title %}Thank you{% endblock %}
{% block header %}Thanks you for your mail.{% endblock %}

{% block content %}
<p>und noch etwas bla text.</p>
{% endblock %}

mysite/templates/current_datetime.html
{% extends "base.html" %}

{% block title %}The current time{% endblock %}
{% block header %}The current time{% endblock %}

{% block content %}
<p>It is now {{ current_date }}.</p>
{% endblock %}

mysite/templates/footer.html
<hr>
<p>Thanks for visiting my site.</p>
</body>
</html>

mysite/templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>

mysite/templates/hours_ahead.html
{% extends "base.html" %}

{% block title %}Future time{% endblock %}
{% block header %}Future time{% endblock %}

{% block content %}
<div class="ahead">
<p>In {{ hour_offset }} hour(s), it will be {{ next_time }}.</p>
</div>
{% endblock %}

mysite/templates/search_form.html
<html>
<head>
	<title>Search</title>
</head>
<body>
	{% if errors %}
	<ul>
		{% for error in errors %}
		<li>{{ error }}</li>
		{% endfor %}
	</ul>
	{% endif %}
	<form action="" method="get">
		<input type="text" name="q">
		<input type="submit" value="Search">
	</form>
</body>
</html>

mysite/templates/search_results.html
<p>You searched for: <strong>{{ query }}</strong></p>
{% if books %}
<p>Found {{ books|length }} book{{ books|pluralize }}.</p>
<ul>
{% for book in books %}
<li>{{ book.title }}</li>
{% endfor %}
</ul>
{% else %}
<p>No books matched your search criteria.</p>
{% endif %}